version: "3.9"
services:
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    ports:
      - "3000:3000"
    environment:
      ES_HOST: es
    depends_on:
      - es
  es:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:7.6.0
    ports:
      - "9200:9200"
    environment:
      discovery.type: single-node
      cluster.name: elasticsearch-rails
      cluster.routing.allocation.disk.threshold_enabled: 'false'
